services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        env_file:
            - .env.local
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres:
