services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        env_file:
            - ./.env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSRGRES_PASSWORD}
            POSTGRES_DB: ${POSRGRES_DATABASE}
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres:
