services:
    api:
        image: gabriel-api
        container_name: api
        ports:
            - "3001:3001"
        networks:
            - gabriel
        env_file:
            - .env.local
        depends_on:
            - postgres
    bot:
        image: gabriel-bot
        container_name: bot
        networks:
            - gabriel
        env_file:
            - .env.local
        depends_on:
            - api
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        env_file:
            - .env.local
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - gabriel
networks:
    gabriel:
volumes:
    postgres:
