name: CI
on:
    push:
        branches:
            - master
    pull_request:

env:
    NX_CLOUD_DISTRIBUTED_EXECUTION: true # this enables DTE
    NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3 # expected number of agents
    NX_BRANCH: ${{ github.event.number || github.ref_name }}
    NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # this is needed if our pipeline publishes to npm

jobs:
    main:
        name: Nx Cloud - Main Job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: Checkout [Pull Request]
              if: ${{ github.event_name == 'pull_request' }}
              with:
                  # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
                  ref: ${{ github.event.pull_request.head.sha }}
                  # We need to fetch all branches and commits so that Nx affected has a base to compare against.
                  fetch-depth: 0
            - uses: mansagroup/nrwl-nx-action@v3
              with:
                  targets: lint,build,deploy
                  nxCloud: true
